source "https://rubygems.org"

gem "sinatra-activerecord"
gem "activerecord"
gem "mysql2"
gem "bcrypt"
gem "sinatra-contrib"
gem "rack-flash3"
gem "sinatra"
gem "rake"
gem "pry-byebug"
gem "pry-doc"
gem "dotenv"